version: "3"

tasks:
    generate:
        aliases:
            - gen
        desc: "Generate storage file"   
        cmds:
            - go run ./cmd/migrator/ --storage-path=./storage/sso.db --migrations-path=./migrations
    setup:
        aliases:
            - run
        desc: "Run app with config"
        cmds:
            - go run ./cmd/sso/ --config=./config/local.yaml    
    generate_test:
        aliases:
            - gen
        desc: "Generate test migrations"   
        cmds:
            - go run ./cmd/migrator/ --storage-path=./storage/sso.db --migrations-path=./tests/migrations --migrations-table=migrations_test                 